id: P003201
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD17634
  title: འཛམ་གླིང་སྐྱེས་མཆོག་སེང་ཆེན་ནོར་བུ་དགྲ་འདུལ་གྱི་རྣམ་པར་ཐར་བ་མུ་ཏིག་ཕྲེང་མཛེས་ལས།
    རོང་གླིང་གཡུལ་འགྱེད།
  author: ''
  volumes:
    c3b63e1f6485401cb387c23e801115f5:
      image_group_id: I2PD19280
      title: ''
      volume_number: 1
      total_pages: 306
      base_file: v001.txt
