id: P003201
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD17634
  title: འཛམ་གླིང་སྐྱེས་མཆོག་སེང་ཆེན་ནོར་བུ་དགྲ་འདུལ་གྱི་རྣམ་པར་ཐར་བ་མུ་ཏིག་ཕྲེང་མཛེས་ལས།
    རོང་གླིང་གཡུལ་འགྱེད།
  author: ''
  volumes: {}
