id: I995E5BB4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T11:07:46+00:00'
last_modified: '2022-06-07T18:21:51.348801+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD17634
  title: འཛམ་གླིང་སྐྱེས་མཆོག་སེང་ཆེན་ནོར་བུ་དགྲ་འདུལ་གྱི་རྣམ་པར་ཐར་བ་མུ་ཏིག་ཕྲེང་མཛེས་ལས།
    རོང་གླིང་གཡུལ་འགྱེད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    104B:
      image_group_id: I2PD19280
      title: ''
      total_pages: 306
      order: 1
      base_file: 104B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
